inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'test/dummy/**/*'
    - 'app/controllers/kaui/engine_controller.rb' # Too much magic going on
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Alternative?
Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty
