#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
KAUI_ROOT_PATH = Pathname.new(__FILE__).realpath.dirname.parent
SANDBOX_ROOT_PATH = "#{KAUI_ROOT_PATH}/sandbox".freeze

require 'fileutils'
require 'rails/generators'
require 'rails/generators/rails/app/app_generator'

$LOAD_PATH.unshift("#{KAUI_ROOT_PATH}/lib")
require 'kaui/installer/installer'

puts "Deleting old sandbox #{SANDBOX_ROOT_PATH}"
FileUtils.rm_rf SANDBOX_ROOT_PATH

puts 'Creating the new Rails app'
ARGV = [SANDBOX_ROOT_PATH, '--skip-bundle'].freeze
Rails::Generators::AppGenerator.start

puts 'Setting up Kaui'
installer_args = [SANDBOX_ROOT_PATH, "--path=#{KAUI_ROOT_PATH}", '--skip-bundle'].freeze
KauiCmd::Installer.start(installer_args)

FileUtils.rm_f "#{SANDBOX_ROOT_PATH}/public/index.html"

puts 'Running migrations'
Dir.chdir SANDBOX_ROOT_PATH
system 'rake kaui:install:migrations'
system 'rake db:migrate'
